dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- sudo pip install conan --ignore-installed
#- mkdir build && cd build
#- conan install .
#- cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ustanislavkuskov:$BINTRAY_API_KEY "https://api.bintray.com/content/stanislavkuskov/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
